name: Update Film Data

on:
  schedule:
    - cron: '*/30 * * * *' 
    - cron: '0 0 */3 * *'
  repository_dispatch:
    types: [update-film]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check Pending Queue
        id: check_step
        if: github.event_name != 'repository_dispatch'
        run: python scripts/check_queue.py
        continue-on-error: false 

      - name: Install dependencies
        run: pip install requests letterboxdpy

      - name: Run Processing Script
        run: |
          if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            python scripts/update_films.py ${{ github.event.client_payload.slug }} ${{ github.event.client_payload.rating_i }} ${{ github.event.client_payload.rating_v }}
          else
            python scripts/process_queue.py
          fi

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add src/data/
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Automated queue/data update"
            git push
          fi
