name: Update Film Data

on:
  repository_dispatch:
    types: [update-film]
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests letterboxdpy

      - name: Run Update Script
        run: python scripts/update_films.py ${{ github.event.client_payload.slug }} ${{ github.event.client_payload.rating_i }} ${{ github.event.client_payload.rating_v }}

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Adicionamos TODOS os arquivos que podem ser alterados pelo Python
          git add src/data/films_stats.json \
                  src/data/films_stats_bkp.json \
                  src/data/igor_watched.json \
                  src/data/couple_watched.json \
                  src/data/failed_films.json
          
          # Usamos um check mais amigável: se o status não estiver vazio, commita
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update film data/queue: ${{ github.event.client_payload.slug }}"
            git push
          else
            echo "Nada para atualizar no repositório."
          fi
