name: Update Film Data

on:
  repository_dispatch:
    types: [update-film]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          # Garante que temos permissão para dar push de volta
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests letterboxdpy

      - name: Run Update Script
        # O payload enviado pelo front deve conter a chave "slugs"
        run: python scripts/update_films.py ${{ github.event.client_payload.slugs }}

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          # Adiciona o arquivo principal e o backup conforme solicitado
          git add src/data/films_stats.json src/data/films_stats_bkp.json
          
          # Só faz o commit se houver mudanças reais para evitar erro na Action
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update films: ${{ github.event.client_payload.slugs }}" && git push)
